//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MagicLantern
{
    [Serializable]
    public class ErrorStatusMsg : Message
    {
        public const string k_RosMessageName = "magic_lantern_msgs/ErrorStatus";
        public override string RosMessageName => k_RosMessageName;

        public bool no_error;
        //  flag indicates error in the program

        public ErrorStatusMsg()
        {
            this.no_error = false;
        }

        public ErrorStatusMsg(bool no_error)
        {
            this.no_error = no_error;
        }

        public static ErrorStatusMsg Deserialize(MessageDeserializer deserializer) => new ErrorStatusMsg(deserializer);

        private ErrorStatusMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.no_error);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.no_error);
        }

        public override string ToString()
        {
            return "ErrorStatusMsg: " +
            "\nno_error: " + no_error.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
