//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MagicLantern
{
    [Serializable]
    public class TrackingStatusMsg : Message
    {
        public const string k_RosMessageName = "magic_lantern_msgs/TrackingStatus";
        public override string RosMessageName => k_RosMessageName;

        public bool worldTracking;
        public bool anchorTracking;

        public TrackingStatusMsg()
        {
            this.worldTracking = false;
            this.anchorTracking = false;
        }

        public TrackingStatusMsg(bool worldTracking, bool anchorTracking)
        {
            this.worldTracking = worldTracking;
            this.anchorTracking = anchorTracking;
        }

        public static TrackingStatusMsg Deserialize(MessageDeserializer deserializer) => new TrackingStatusMsg(deserializer);

        private TrackingStatusMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.worldTracking);
            deserializer.Read(out this.anchorTracking);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.worldTracking);
            serializer.Write(this.anchorTracking);
        }

        public override string ToString()
        {
            return "TrackingStatusMsg: " +
            "\nworldTracking: " + worldTracking.ToString() +
            "\nanchorTracking: " + anchorTracking.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
